### ISSUE TITLE
Taking too long time to update VERSION file

### ISSUE THREAD

**Issue by vinodhraj** [remorses/bump-version#1]
In react-native based mobile project which also has unit test cases with folders in root like "__tests__" and "__mocks__". Have a file "VERSION" in root folder with content as "0.0.1".

Added main.yml file in Github workflow folder with code as below

`name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump Versions
      uses: remorses/bump-version@js
      with:
        version_file: ./VERSION
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
`

On every commit, it takes 20-25 min to complete the job. If I remove "__tests__" folder then time reduces to 3-5 min for job completion. May be it scans all the files in the repo even though target file name and path is mentioned in main.yml.

**Comment by remorses** [comment]
Sorry for the long wait. 
This issue is because the action tries to bump all the versions it finds after the pattern `[bump]`.
I have added an option do disable it, add `skip_patterns: '1'` to the inputs to skip the search.
The argument to the `skip_patterns` can be anything, only when it is an empty string (the default), the pattern will be replaced.
